@startuml
'https://plantuml.com/class-diagram

interface Environment {
    +{abstract}boolean executeAction(Action action, int data);
    +{abstract}int getCurrentState();
    +{abstract}int getStateSpace();
    +{abstract}void tick();
}

@enduml