@startuml
'https://plantuml.com/class-diagram

interface SzenarioProgressObserver {

+{abstract} void onTrainingStart(SzenarioSession session)
+{abstract} void preTrainingStep(SzenarioSession session, long currentStep, double averageReward)
+{abstract} void postTrainingStep(SzenarioSession session, long currentStep, double averageReward)
+{abstract} void onTrainingEnd(SzenarioSession session, double averageReward)

}

@enduml