@startuml

interface EnvironmentFactory {
    +{abstract}Optional<Environment> createEnvironment(EnvironmentDescriptor descriptor, Map<String, String> parameters)
}

class SimpleEnvironmentFactory {
    -{static} Map<String, EnvironmentConstructor> ENV_CONSTRUCTORS
    ---
    +Optional<Environment> createEnvironment(EnvironmentDescriptor descriptor, Map<String, String> parameters)
    ---
    -{static} KArmedBanditEnvironment createKArmedBanditEnvironment(Map<String, String> parameters)
    -{static} GridWorldEnvironment createGridWorldEnvironment(Map<String, String> parameters)
    -{static} int[][] parseGridWorldFile(Path fromPath)
}

note left of SimpleEnvironmentFactory::parseGridWorldFile
    Open file
    foreach line in file do
        parse line
        fill grid array with content
    return grid
end note

EnvironmentFactory <|.. SimpleEnvironmentFactory

@enduml