@startuml
'https://plantuml.com/class-diagram

class RLSettings {
    +double learningRate
    +double discountFactor
    +double explorationRate
    +double agentRewardStepSize
    ---
    -{static} void checkArgumentRangeZeroToOneInclusive(double value, String error)
}

@enduml